### ISSUE TITLE
The mod is kinda broken

### ISSUE THREAD

**Issue by Ilikepieitsgood** [Gwapowo/DuoEnhanced#2]
Look at this 
![Screenshot_20210325-183435_Mindustry BE](https://user-images.githubusercontent.com/78336842/112556748-d69b9d00-8d98-11eb-90e5-16b254e3154b.jpg)
And core duo literally just gives alpha

**Comment by Ilikepieitsgood** [comment]
Ok almost nothing actually works

**Comment by LostCause122** [comment]
I can tell 
[Uploading 43904…]()

**Comment by Gwapowo** [comment]
I just changed minVersion to v6 without changing anything to see what'll happen, will fix all issues once I change all code to be portable for v6.

**Comment by Duo-Turret** [comment]
Send me the code.

**Comment by Gwapowo** [comment]
Mod has been ported to v6 and issues have been fixed, yay

**Comment by Gwapowo** [comment]
> Send me the code.

You can find the code in GitHub itself, which is in the code section.
